# Generated by Django 3.2.20 on 2023-08-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('valor', models.FloatField(verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('categoria_empresa', models.CharField(max_length=200, verbose_name='CNPJ')),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.stand')),
            ],
        ),
    ]
