# Generated by Django 3.2.20 on 2023-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='categoria_empresa',
            field=models.CharField(max_length=200, verbose_name='Categoria da empresa'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
