# Generated by Django 3.2.20 on 2023-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_auto_20230830_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quitado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
