# Generated by Django 3.2.20 on 2023-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_reserva_quitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria_empresa',
            field=models.CharField(choices=[('telecomunicação', 'Telecomunicação'), ('fast-food', 'Fast-Food'), ('marketing', 'Marketing'), ('cultura', 'Cultura')], max_length=200, verbose_name='Categoria da empresa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quitado',
            field=models.BooleanField(default=False),
        ),
    ]
