# Generated by Django 4.2.5 on 2023-09-20 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_auto_20230831_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
